server:
  port: 11002
spring:
  data:
    redis:
      host: redis
      port: 6379
      password: redis
      timeout: 3000ms # 连接超时时间
      lettuce:
        pool:
          max-active: 8 # 连接池最大连接数
          max-idle: 8 # 连接池最大空闲连接数
          min-idle: 0 # 连接池最小空闲连接数
          max-wait: -1ms # 连接池最大阻塞等待时间，负值表示没有限制
springdoc:
  swagger-ui:
    enabled: false
  show-actuator: false
upload:
  pdf:
    path: resume/pdf


ai:
  openai:
    api-key: "your api key"
    base-url: "base url"
    debug: false